backend:
  name: git-gateway
  branch: main # Or your default branch

media_folder: "images/uploads" # Where images will be stored
public_folder: "/images/uploads" # Public path for images

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "images/uploads"
    create: true
    fields:
      - { name: "title", label: "Image Title", widget: "string" }
      - { name: "image", label: "Image", widget: "image" }